# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  notify-start:
    runs-on: ubuntu-latest
    
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ci-test
          SLACK_COLOR: '#7fe5f0'
          SLACK_MESSAGE: 'Starting CI :runner:'
          SLACK_TITLE: A new PR has been opened
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # checkout
    - uses: actions/checkout@v2
    
    # set the required runtime
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    # test
    - name: Run unit tests
      run: mvn -B test --file pom.xml

    # publish test results
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.7
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: target/**/*.xml

    # build
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # stage the artifact
    - run: mkdir staging && cp target/*.jar staging

    # upload the artifact
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

    - name: Report Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ci-test
        SLACK_COLOR: '#F7347A'
        SLACK_MESSAGE: 'CI failed! :rotating_light:'
        SLACK_TITLE: CI Failed!
        SLACK_USERNAME: GitHub Actions
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
   
  notify-success:
    needs: [build-and-test, notify-start]
    runs-on: ubuntu-latest
    
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ci-test
          SLACK_COLOR: '#5AC18E'
          SLACK_MESSAGE: 'CI was succesful! :rocket:'
          SLACK_TITLE: Build Succesful!
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}